version: '3'

services:
  mariadb-docker-container:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=131285bazar
      - MARIADB_DATABASE=bazar_db
      - MARIADB_USER=bazar_db_user
      - MARIADB_PASSWORD=1qaz
    volumes:
      - /data/mariadb
  bazar-app:
    image: bazar:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mariadb-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/bazar-app